language: rust
cache: cargo
sudo: false
os:
- linux
- osx
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of coveralls
      - libiberty-dev # same
rust:
  - nightly
  - beta
  - stable

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python || true; fi

# load travis-cargo
before_script:
  - pip install 'travis-cargo<0.2' --user
  - if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
  - if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
  - echo PATH is $PATH
  - export RUST_BACKTRACE=1

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench

after_success:
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        rm -f target/debug/deps/read_process_memory-*
        travis-cargo coveralls --no-sudo --verify
        set -v -x
        # Workaround for https://github.com/huonw/travis-cargo/issues/58
        for f in target/debug/deps/read_process_memory-*; do
          ./kcov/build/src/kcov --verify --exclude-pattern=/.cargo --include-pattern=$PWD target/kcov $f
        done
        ./kcov/build/src/kcov --merge --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --include-pattern=$PWD target/kcov target/kcov
        set +v +x
      fi

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
